package Model;
// Generated 17/05/2016 02:10:33 PM by Hibernate Tools 4.3.1



/**
 * Puntos generated by hbm2java
 */
public class Puntos  implements java.io.Serializable {


     private long id;
     private Area area;
     private double x;
     private double y;

    public Puntos() {
    }

    public Puntos(long id, Area area, double x, double y) {
       this.id = id;
       this.area = area;
       this.x = x;
       this.y = y;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public double getX() {
        return this.x;
    }
    
    public void setX(double x) {
        this.x = x;
    }
    public double getY() {
        return this.y;
    }
    
    public void setY(double y) {
        this.y = y;
    }




}


