package Model;
// Generated 17/05/2016 02:10:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Terreno generated by hbm2java
 */
public class Terreno  implements java.io.Serializable {


     private long id;
     private String direccion;
     private double total;
     private String descripcion;
     private Set areas = new HashSet(0);

    public Terreno() {
    }

	
    public Terreno(long id, String direccion, double total, String descripcion) {
        this.id = id;
        this.direccion = direccion;
        this.total = total;
        this.descripcion = descripcion;
    }
    public Terreno(long id, String direccion, double total, String descripcion, Set areas) {
       this.id = id;
       this.direccion = direccion;
       this.total = total;
       this.descripcion = descripcion;
       this.areas = areas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set areas) {
        this.areas = areas;
    }




}


